### ISSUE TITLE
curlにレスポンスできるようにしよう

### ISSUE THREAD

**Issue by ToYeah** [JUNNETWORKS/42-webserv#7]
# 概要
curlできたリクエストにhttp経由で返答できるようにする。
ファイルの検索等は行わず、いったんレスポンスを返すことが目標。
# 目的
curlで動いてるところをみてアガりたい
# 提案内容
POLLOUTのイベントで対応するソケットにHTTPヘッダ付きのレスポンスを書き込む機能をつける
# タスク
- [ ] httpリクエストクラスを完成させる

**Comment by ToYeah** [comment]
#11 
レスポンスは一応返るようになった

**Comment by JUNNETWORKS** [comment]
これCloseしてよくね
