### ISSUE TITLE
複数クライアントをシミュレートするような client.py 的なのが欲しい｡

### ISSUE THREAD

**Issue by JUNNETWORKS** [JUNNETWORKS/42-webserv#71]
n個のクライアントが同時にリクエストを送ってくる状況で webserv が正しく動くかテストしたい｡

**Comment by s-xix98** [comment]
めっちゃリクエスト送る系とか、
一気に全部リクエスト送信しないで、時間差でくるとかあると思うけど、
どっちも必要って感じかな？

webserv が正しく動くかテストというのは、レスポンスしてないものがある、内容が正しいとか色々あると思うけど、
具体的に何がみたいとかあったりする？
その辺、何かあれば聞いときたいかも

**Comment by JUNNETWORKS** [comment]
負荷試験ソフト

[Locust](https://locust.io/)

**Comment by JUNNETWORKS** [comment]
## 目的

イベントループが複数の接続を処理できるか確かめたい｡

処理できるのであればどのくらいの同時接続まで耐えれられるか知りたい｡

## 自分の考え

- 基本正常系のリクエストが送られてくる想定｡
- 時間差で来るのはたしかに欲しいかもしれないが優先度は高くない｡複数クライアントからリクエストが送られてくる状況を再現したい｡
- レスポンスの内容が正しいかは確認したいが､確認するのはHTTPステータスコードくらいで良い｡レスポンスボディまでは見なくて良い認識｡
