### ISSUE TITLE
チャンク区切りされたHTTPリクエストを処理できる

### ISSUE THREAD

**Issue by JUNNETWORKS** [JUNNETWORKS/42-webserv#9]
# 概要
# 目的
# 提案内容
# タスク
- [ ] 細かいタスクに分解できているなら書き出す

**Comment by ToYeah** [comment]
未知のTransfer-encodingが来たときは501
http://itdoc.hitachi.co.jp/manuals/link/cosmi_v0870/APKW/EU050269.HTM
![501](https://user-images.githubusercontent.com/62199197/173240638-b879084d-3888-4d99-a914-58a565aa5509.png)

**Comment by ToYeah** [comment]
Transfer-EncodingとContent-Lengthが両方あるときはBAD Request
APACHEは上書きと片方無視とかしてるかも
![ew](https://user-images.githubusercontent.com/62199197/173241558-5ed56138-254c-452e-bfe6-206f489e2995.png)

**Comment by ToYeah** [comment]
http://www.silex.jp/blog/wireless/2016/02/http.html#:~:text=%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82-,Transfer%2DEncoding,-HTTP/1.0%20%E3%81%A7

**Comment by ToYeah** [comment]
![aa](https://user-images.githubusercontent.com/62199197/173245968-736b9736-da1e-4984-b2b3-33e202f6ad3f.png)
